version: "3.9"
networks: 
    laravel:
services:  
  php:
    networks: 
     - laravel
    image: php:7.3-fpm
    volumes: 
      - ./site/:/var/www/myapp
    container_name: demo1
    working_dir: /var/www/myapp #địa chỉ vô cont
    command: bash -c "php-fpm" # Giữ container ko bị chết
    ports: 
      - 81:80
  nginx:
  networks: 
     - laravel
    image: nginx:1.19
    ports: 
      - 80:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./site/:/var/www/myapp
    working_dir: /var/www/myapp
  mysql:
    networks: 
     - laravel
     image: mysql:5.7.22
     container_name: mysql
     restart: unless-stopped
     tty:true
     ports: 
      -"4306:3306"
    volumes: 
     -./mysql:var/lib/mysql
     environment: 
       MYSQL_DATABASE: homestead
       MYSQL_USER: homestead
       MYSQL_PASSWORD: secret
       MY_SQL_ROOT_PASSWORD: secret
       SERVICE_TAGS: dev
       SERVICE_NAME: mysql 

    
    
      