version: "3.9"
services:  
  php:
    image: php:7.3-fpm
    volumes: 
      - ./site/:/var/www/myapp
    container_name: demo1
    working_dir: /var/www/myapp #địa chỉ vô cont
    command: bash -c "php-fpm" # Giữ container ko bị chết
    ports: 
      - 81:80
  nginx:
    image: nginx:1.19
    ports: 
      - 80:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./site/:/var/www/myapp
    working_dir: /var/www/myapp
    
    
      